baseURL = ''
defaultContentLanguage = "en"
languageCode = 'en-us'

title = 'Mehrnoosh'

theme = "congo"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    name = "Posts"
    weight = 1
    pre = "<span data-feather='book'></span>"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    pre = "<span data-feather='tag'></span>"
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/about/"
    weight = 3
    pre = "<span data-feather='user'></span>"

[params]
  showPostsOnHomePage = "recent"

[author]
  name = "Mehenoosh H. Kashani"
  # image = "img/author.jpg"
  headline = "THE ONLY WAY TO FAIL IS TO QUIT"
  bio = "A little bit about me"
  links = [
    { github = "https://github.com/mehrnoosh-hk" },
    { email = "mehrnoosh.h.kashani@gmail.com" },
    { linkedin = "https://www.linkedin.com/in/mehrnoosh-h-kashani/" },
  ]